//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogoWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.LinkButton lnk1;
		
		protected System.Web.UI.WebControls.DataGrid grid;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl fondo;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl flotante;
		
		protected System.Web.UI.WebControls.TextBox codigoText;
		
		protected System.Web.UI.WebControls.DropDownList marcaLista;
		
		protected System.Web.UI.WebControls.DropDownList categoriaLista;
		
		protected System.Web.UI.WebControls.TextBox descripcionText;
		
		protected System.Web.UI.WebControls.TextBox precioText;
		
		protected System.Web.UI.WebControls.Button b2;
		
		protected System.Web.UI.WebControls.Button b1;
	}
}
