//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data;
using System.Web.UI.WebControls;

namespace CatalogoWeb
{
	using System;
	using System.Web;
	using System.Web.UI;

	public partial class Default : System.Web.UI.Page
	{
		CatalogoConsola.Conexion con = new CatalogoConsola.Conexion (@"C:\bd\catalogo.sqlite");
		DataSet dst = new DataSet();

		private void Page_Load(Object s, EventArgs e){
			if (dst.Tables.Count == 0) {
				dst = cargarCatalogo ();
			}

			this.grid.DataSource = dst.Tables[0];
			if (!Page.IsPostBack)
			{
				this.grid.DataBind();
			}
		}

		protected DataSet cargarCatalogo(){
			DataSet l1 = new DataSet ("Autopartes");
			l1.Tables.Add (con.getAutopartes ());
			return l1;
		}

		protected void insertar(Object s, EventArgs e){
			String query = "INSERT INTO autoparte(codigoParte, marca, categoria, descripcion, precio) VALUES ('" + this.codigoText.Text + "','" + this.marcaLista.Text + "','" + this.categoriaLista.Text + "','" + this.descripcionText.Text + "','" + this.precioText.Text + "');";
			if (con.ejecutar (query)) {
				dst = cargarCatalogo ();
				this.grid.DataSource = dst.Tables [0];
				this.grid.DataBind();
			}
			this.fondo.Style.Add("display","none");
			this.flotante.Style.Add("display","none");
			this.codigoText.Text = "";
			this.descripcionText.Text = "";
			this.precioText.Text = "";
		}

		/* FUNCIONES DE EDICION */

		protected void Grid_Editar(Object sender, DataGridCommandEventArgs e){
			grid.EditItemIndex = e.Item.ItemIndex;
			this.grid.DataBind();
		}

		protected void Grid_Cancelar(Object sender, DataGridCommandEventArgs e){
			grid.EditItemIndex = -1;
			this.grid.DataBind();
		}

		protected void Grid_Actualizar(Object sender, DataGridCommandEventArgs e){
			String id =  Convert.ToString(dst.Tables[0].Rows[e.Item.ItemIndex][0]);
			String codigoParte = ((TextBox)e.Item.Cells[0].Controls[0]).Text;
			String marca 	   = ((TextBox)e.Item.Cells[1].Controls[0]).Text;
			String categoria   = ((TextBox)e.Item.Cells[2].Controls[0]).Text;
			String descripcion = ((TextBox)e.Item.Cells[3].Controls[0]).Text;
			String precio      = ((TextBox)e.Item.Cells[4].Controls[0]).Text;

			String query = "UPDATE autoparte SET codigoParte='" + codigoParte + "', marca='" + marca + "', categoria='" + categoria + "', descripcion='" + descripcion + "', precio=" + precio + " WHERE id='" + id + "'";

			if (con.ejecutar (query)) {
				dst.Tables[0].Rows[e.Item.ItemIndex][1] = codigoParte;
				dst.Tables[0].Rows[e.Item.ItemIndex][2] = marca;
				dst.Tables[0].Rows[e.Item.ItemIndex][3] = categoria;
				dst.Tables[0].Rows[e.Item.ItemIndex][4] = descripcion;
				dst.Tables[0].Rows[e.Item.ItemIndex][5] = precio;
			}

			grid.EditItemIndex = -1;
			this.grid.DataBind();
		}

		protected void Grid_Comando(Object sender, DataGridCommandEventArgs e){
			switch (((LinkButton)e.CommandSource).CommandName)
			{
			case "btnEliminar":
				{
					String id =  Convert.ToString(dst.Tables[0].Rows[e.Item.ItemIndex][0]);
					if(con.ejecutar("DELETE FROM autoparte WHERE id='" + id + "'")){
						dst.Tables[0].Rows.RemoveAt(e.Item.ItemIndex);
						this.grid.DataBind();
					}
					break;
				}

			default:
				break;
			}
		}

		protected void cancelar(Object s, EventArgs e){
			this.fondo.Style.Add("display","none");
			this.flotante.Style.Add("display","none");
		}

		protected void mostrar(Object s, EventArgs e){
			this.fondo.Style.Add("display","block");
			this.flotante.Style.Add("display","block");
		}
	}
}

